### ISSUE TITLE
Crash in Simon_087.mj

### ISSUE THREAD

**Issue by kit-fw** [OliverSch/compiler#106]
Urgh das wurde durch den Commit getriggert der Inlining von print und calloc erlaubt. Aber keine Ahnung was da der zu grunde liegende fail ist. 

````
felix@ubuntu:~/compiler$ ./run mj-test/run/Simon_087.mj
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5005f6bcc2, pid=43807, tid=139982214092544
#
# JRE version: OpenJDK Runtime Environment (8.0_40-b09) (build 1.8.0_40-internal-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.40-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libfirm.so+0x72cc2]  get_kind+0xc
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/felix/compiler/hs_err_pid43807.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
JNA: Callback firm.Firm$3@544fe44c threw the following exception:
java.lang.RuntimeException: Prog Aborted
	at firm.Firm$3.callback(Firm.java:76)
	at firm.bindings.binding_irnode.get_irn_opcode(Native Method)
	at firm.nodes.Node.createWrapper(Node.java:30)
	at firm.BackEdges$EdgeIterator.next(BackEdges.java:52)
	at firm.BackEdges$EdgeIterator.next(BackEdges.java:31)
	at edu.kit.pp.mjcompiler.mjcompiler.firm.FirmUtil.getSuccessor(FirmUtil.java:46)
	at edu.kit.pp.mjcompiler.mjcompiler.firm.optimize.MethodInline.inline(MethodInline.java:75)
	at edu.kit.pp.mjcompiler.mjcompiler.firm.optimize.MethodInline.perform(MethodInline.java:55)
	at edu.kit.pp.mjcompiler.mjcompiler.firm.FirmProgram.optimize(FirmProgram.java:136)
	at edu.kit.pp.mjcompiler.CompileCommand.generateOptimizedCode(CompileCommand.java:66)
	at edu.kit.pp.mjcompiler.CompileCommand.execute(CompileCommand.java:48)
	at edu.kit.pp.mjcompiler.CompileCommand.execute(CompileCommand.java:15)
	at edu.kit.pp.mjcompiler.Main.lambda$main$0(Main.java:21)
	at edu.kit.pp.mjcompiler.Main$$Lambda$1/627150481.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at edu.kit.pp.mjcompiler.Main.main(Main.java:16)
Aborted (core dumped)
````

**Comment by felixwilhelm** [comment]
"fixed" with commit 86c771938206f17080e45185fdf8422f2c30ecf9 that disables inlining of methods that include function calls. This sacrifices performance but works correctly for all our test cases.
