### ISSUE TITLE
prometheus5.mj crashes

### ISSUE THREAD

**Issue by felixwilhelm** [OliverSch/compiler#91]
```---FIRM---
Created program prometheus5
192
---CUSTOM---
Exception in thread "main" java.lang.NullPointerException
	at edu.kit.pp.mjcompiler.asm.codegen.SlotAllocator$1.create(SlotAllocator.java:154)
	at edu.kit.pp.mjcompiler.asm.codegen.SlotAllocator$1.create(SlotAllocator.java:61)
	at edu.kit.pp.mjcompiler.common.FlyWeightFactory.getValue(FlyWeightFactory.java:21)
	at edu.kit.pp.mjcompiler.asm.codegen.SlotAllocator.run(SlotAllocator.java:175)
	at edu.kit.pp.mjcompiler.asm.codegen.FirmToIntermediate$NodeAssembler.<init>(FirmToIntermediate.java:251)
	at edu.kit.pp.mjcompiler.asm.codegen.FirmToIntermediate.emitAssembler(FirmToIntermediate.java:227)
	at edu.kit.pp.mjcompiler.asm.codegen.FirmToIntermediate.execute(FirmToIntermediate.java:112)
	at edu.kit.pp.mjcompiler.asm.codegen.FirmToIntermediate.convert(FirmToIntermediate.java:63)
	at edu.kit.pp.mjcompiler.asm.codegen.CodeGeneration.build(CodeGeneration.java:16)
	at edu.kit.pp.mjcompiler.asm.codegen.CodeGeneration.perform(CodeGeneration.java:22)
	at edu.kit.pp.mjcompiler.mjcompiler.firm.CodeGen$CodeGenCustom.run(CodeGen.java:55)
	at edu.kit.pp.mjcompiler.mjcompiler.firm.FirmProgram.generateCode(FirmProgram.java:101)
	at edu.kit.pp.mjcompiler.CompileCommand.generateOptimizedCode(CompileCommand.java:69)
	at edu.kit.pp.mjcompiler.CompileCommand.execute(CompileCommand.java:48)
	at edu.kit.pp.mjcompiler.CompileCommand.execute(CompileCommand.java:15)
	at edu.kit.pp.mjcompiler.Main.lambda$main$0(Main.java:21)
	at edu.kit.pp.mjcompiler.Main$$Lambda$1/627150481.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at edu.kit.pp.mjcompiler.Main.main(Main.java:16)
```

**Comment by felixwilhelm** [comment]
@olydis : Falls du es noch nicht bemerkt hast ;)
