### ISSUE TITLE
Unitialized.java

### ISSUE THREAD

**Issue by felixwilhelm** [OliverSch/compiler#97]
````
class A {
	public static void main(String[] args) {}

	public int foo()
	{
		int[] arr;
		return arr[0];
	}
}
````

**Comment by felixwilhelm** [comment]
````Exception in thread "main" org.apache.commons.lang3.NotImplementedException: did not expect Unknown node
	at edu.kit.pp.mjcompiler.asm.codegen.FirmToIntermediate$NodeAssembler.visit(FirmToIntermediate.java:658)
	at firm.nodes.Unknown.accept(Unknown.java:25)
	at edu.kit.pp.mjcompiler.asm.codegen.FirmToIntermediate.emitAssembler(FirmToIntermediate.java:228)````
